description: ""
# ---------- Technical ----------
random_seed: null
use_cuda: true
debug: false
cudnn_enabled: true
cudnn_benchmark: true
cudnn_deterministic: false
cuda_non_blocking: true
fp16_train: false # this will create NaN in the backward pass!
fp16_val: false
# ---------- Training ----------
train:
    batch_size: 16
    num_epochs: 30
    loss_func: "crossentropy"
    clip_gradient: 1
label_smoothing: 0.1
# ---------- Validation ----------
val:
    batch_size: 8
    val_freq: 1
    val_start: 0
    det_best_field: "cider"
    det_best_compare_mode: "max"
    det_best_threshold_mode: "rel"
    det_best_threshold_value: 1e-4
    det_best_terminate_after: 10
save_mode: "best"
# ----- beam search -----
use_beam: False
beam_size: 2
n_best: 1
# generated sentence bounds
min_sen_len: 5
max_sen_len: 30
block_ngram_repeat: 0
length_penalty_name: "none"
length_penalty_alpha: 0.
# ---------- Dataset / Dataloader ----------
dataset_train:
    name: "BILA"
    split: "train"
    shuffle: true
    pin_memory: true
    num_workers: 4
dataset_val:
    same_as: "dataset_train"
    shuffle: false
    split: "val"
max_n_sen: 12 # 6 activitynet, 12 youcook2
max_n_sen_add_val: 10
max_t_len: 55
max_v_len: 8 # img_num + 2
type_vocab_size: 2
word_vec_size: 173
# ---------- Model ----------
attention_probs_dropout_prob: 0.1
hidden_dropout_prob: 0.1
clip_dim: 768
hidden_size: 768
intermediate_size: 768
layer_norm_eps: 1e-12
memory_dropout_prob: 0.1
num_attention_heads: 12
num_hidden_layers: 2
n_memory_cells: 1
share_wd_cls_weight: false
fix_emb: true
cross_attention_layers: 2
ca_embedder : "Base"
# ---------- Uniter ----------------
uniter_hidden_size: 768
uniter_hidden_dropout_prob: 0.1
uniter_img_dim: 1024
uniter_pos_dim: 7
# ---------- Optimization ----------
ema_decay: 0.9999
initializer_range: 0.02
lr: 0.0001
lr_warmup_proportion: 0.1
# ---------- Logging ----------
logging:
    step_train: 10
    step_val: 10
    step_gpu: -1
    step_gpu_once: 10
# ---------- Saving ----------
saving:
    keep_freq: -1
    save_last: true
    save_best: true
    save_opt_state: true
# ------ knn ------
dstore_keys_path: "checkpoints/dstore_keys.npy"
dstore_vals_path: "checkpoints/dstore_vals.npy"
dstore_size: 100000
k_num: 10
alpha: 0.25
dstore_id_num: 56100
knn_temperature: 100 # TODO: 変更
